defmodule Mintacoin.Crypto.Stellar.Payments do
  @moduledoc """
  This module provides functions to interact with payments in the Stellar network.
  """

  alias Mintacoin.Crypto.PaymentCreated

  @spec create(params :: map()) :: {:ok, struct()}
  def create(_params) do
    {:ok,
     %PaymentCreated{
       source_secret: "SCP6HOQYN57RWQHVDPTPDGV3FMTYL3AULW3A26S5XTB2UNMZ52IFL5FN",
       destination_secret: "SAHGVCA37V54AACEYNDLNIB356BWV3WEALMYFOAVX2OE24SZCIBDRO4X",
       asset: [code: "MTK", issuer: "GA2YG3YULNTUEMMLN4HUQVL7B37GJTYSRZYH6HZUFLXFDCCGKLXIXMDT"],
       amount: 1000,
       successful: true,
       tx_json: %{
         created_at: ~U[2022-06-29 21:53:00Z],
         envelope_xdr:
           "AAAAAgAAAAA1g28UW2dCMYtvD0hVfw7+ZM8SjnB/HzQq7lGIRlLuiwAAAGQAAc5vAAAABQAAAAAAAAAAAAAAAQAAAAAAAAABAAAAADqwUtg1Z2W2ioK5oidVOy7ezJidLD4oJ6sdOFj6QzNKAAAAAAAAAAAO5rKAAAAAAAAAAAFGUu6LAAAAQAKtIbNz3iWymPeZSugaqWTpiM81VIYedaRlIOcR2SM6+ckueHyqSKYWxmsNAFGW5NJtF38mJt8xk2RFOKONnAc=",
         fee_charged: 100,
         fee_meta_xdr:
           "AAAAAgAAAAMAAd+tAAAAAAAAAAA1g28UW2dCMYtvD0hVfw7+ZM8SjnB/HzQq7lGIRlLuiwAAABdHRblwAAHObwAAAAQAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAAB360AAAAAYrzJaAAAAAAAAAABAAHfvQAAAAAAAAAANYNvFFtnQjGLbw9IVX8O/mTPEo5wfx80Ku5RiEZS7osAAAAXR0W5DAABzm8AAAAEAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAAAAd+tAAAAAGK8yWgAAAAA",
         hash: "ad9ce37da535471089839da43b007929c17bee4aa747b944e3954efa44472537",
         id: "ad9ce37da535471089839da43b007929c17bee4aa747b944e3954efa44472537",
         ledger: 122_813,
         max_fee: 100,
         memo: nil,
         memo_type: "none",
         operation_count: 1,
         paging_token: "527477818548224",
         result_meta_xdr:
           "AAAAAgAAAAIAAAADAAHfvQAAAAAAAAAANYNvFFtnQjGLbw9IVX8O/mTPEo5wfx80Ku5RiEZS7osAAAAXR0W5DAABzm8AAAAEAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAAAAd+tAAAAAGK8yWgAAAAAAAAAAQAB370AAAAAAAAAADWDbxRbZ0Ixi28PSFV/Dv5kzxKOcH8fNCruUYhGUu6LAAAAF0dFuQwAAc5vAAAABQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAAHfvQAAAABivMm8AAAAAAAAAAEAAAAEAAAAAwAB370AAAAAAAAAADWDbxRbZ0Ixi28PSFV/Dv5kzxKOcH8fNCruUYhGUu6LAAAAF0dFuQwAAc5vAAAABQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAAHfvQAAAABivMm8AAAAAAAAAAEAAd+9AAAAAAAAAAA1g28UW2dCMYtvD0hVfw7+ZM8SjnB/HzQq7lGIRlLuiwAAABc4XwaMAAHObwAAAAUAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAAB370AAAAAYrzJvAAAAAAAAAADAAHPZAAAAAAAAAAAOrBS2DVnZbaKgrmiJ1U7Lt7MmJ0sPignqx04WPpDM0oAAAAAATEtAAABz2QAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAHfvQAAAAAAAAAAOrBS2DVnZbaKgrmiJ1U7Lt7MmJ0sPignqx04WPpDM0oAAAAAEBffgAABz2QAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA",
         result_xdr: "AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAA=",
         signatures: [
           "Aq0hs3PeJbKY95lK6BqpZOmIzzVUhh51pGUg5xHZIzr5yS54fKpIphbGaw0AUZbk0m0XfyYm3zGTZEU4o42cBw=="
         ],
         source_account: "GA2YG3YULNTUEMMLN4HUQVL7B37GJTYSRZYH6HZUFLXFDCCGKLXIXMDT",
         source_account_sequence: 508_451_113_402_373,
         successful: true,
         valid_after: nil,
         valid_before: nil
       }
     }}
  end
end
